[package]
name = "lm"
version = "0.1.0"
authors = ["XorTroll"]
edition = "2018"

[dependencies]
nx = { git = "https://github.com/aarch64-switch-rs/nx" }
paste = "1.0"

[package.metadata.nx.nsp]
npdm = "npdm.json"